apiVersion: apps/v1
kind: Deployment
metadata:
  name: gas-price-worker
  labels:
    app.kubernetes.io/name: gas-price-worker
    app.kubernetes.io/part-of: distributed-gas-price-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gas-price-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gas-price-worker
        app.kubernetes.io/part-of: distributed-gas-price-platform
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: worker
          image: ghcr.io/ni-da-ba/distributed-gas-price-platform:1.0.1
          imagePullPolicy: IfNotPresent
          command: ["python", "-m", "gas_price_platform.worker"]
          envFrom:
            - configMapRef:
                name: gas-price-config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 750m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: temporary-files
              mountPath: /tmp
      volumes:
        - name: temporary-files
          emptyDir: {}
